#!/bin/bash
sudo systemctl start httpd
cd /var/www/html/
DIR="/var/www/html/roshandevops"
if [ -d "$DIR" ]; then
    echo "${DIR} exists"
    sudo git -C "$DIR" pull
else
    sudo git clone https://github.com/roshansibi/roshandevops "$DIR"
fi