name: Deploy to GitHub pageson:
  push:
   
    branches: [ main ]jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run a multi-line script
      run: |
        echo test the checkout action,
        ls -a
   
