name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy to web server
      uses: appleboy/scp-action@master
      with:
        host: 192.168. 1.2
        username: roshansibi
        password: ${{ secrets.SERVER_PASSWORD }} 
        source: index.html
        target: https://github.com/roshansibi/roshandevops/blob/master/index.html
