name: Deploy to EC2-2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH client
        run: sudo apt-get install -y openssh-client

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY1 }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      - name: Connect to EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST1 }}
          username: ${{ secrets.EC2_USERNAME1 }}
          key: ${{ secrets.SSH_PRIVATE_KEY1 }}
          script: |
            cd /var/www/html
            sudo git pull origin main
            sudo service httpd restart
